Initiate UpgradeSubscriptionHandler and DowngradeSubscriptionHandler flow implementation
BroadleafCommerce/SubscriptionOperationServices pull request #16
Opened 2024-10-30 15:26 UTC by karan-j-blc

For ticket: https://github.com/BroadleafCommerce/MicroPM/issues/5167

The Upgrade and Downgrade Handlers are now populated with the AddItemRequest for the new product to upgrade/downgrade to which would then be set on the CreateCartRequest

2024-10-31 20:11 UTC, ckittrell reviewed
A few cleanup items as we figure out the appropriate upgrade/downgrade initiation steps via Slack conversation.

2024-10-31 20:11 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +    }
Can use `@RequiredArgsConstructor` on this class

2024-10-31 20:11 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/DowngradeSubscriptionHandler.java
> +    private CartOperationProvider<Cart> cartOperationProvider;
Provide these beans via the constructor, rather than via setters

2024-10-31 20:11 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/DowngradeSubscriptionHandler.java
> +                                ChronoUnit.DAYS))) {
Code smell note: Having a huge if-condition like this & needing to add a comment to describe what it does is usually a clear sign that the if-condition logic should be used to a method with a meaningful name.

2024-10-31 20:11 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/UpgradeSubscriptionHandler.java
> +    private CartOperationProvider<Cart> cartOperationProvider;
Same note about using the constructor, rather than setters

2024-10-31 20:11 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/UpgradeSubscriptionHandler.java
> +        if (!fetchedProducts.getContent().isEmpty() && fetchedProducts.getContent().size() == 2) {
Use `CollectionUtils.size(...)` instead to avoid silly NPEs & avoid the need to check if empty

2024-10-31 21:17 UTC, ckittrell requested changes

2024-10-31 21:17 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/DowngradeSubscriptionHandler.java
> +        addDependentsToParents(subscriptionItemIdsToChildrenIds, addItemRequestMap);
This needs to setup add-to-cart requests for the downgrade item that we're targeting

2024-10-31 21:17 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/UpgradeSubscriptionHandler.java
> +        addDependentsToParents(subscriptionItemIdsToChildrenIds, addItemRequestMap);
This needs to setup add-to-cart requests for the upgrade item that we're targeting

2024-10-31 21:17 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/UpgradeSubscriptionHandler.java
> +            request.setChangeTo(fetchedProducts.getContent().get(1));
We don't have any reason to expect a specific order here. This needs to iterate through the response to find the matching product.

2024-11-01 07:59 UTC, karan-j-blc commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +    public final TypeFactory typeFactory;
Making it `private` will make it inaccessible in the child classes. Marking it `protected` instead

2024-11-01 08:02 UTC, karan-j-blc commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/DowngradeSubscriptionHandler.java
> +                                ChronoUnit.DAYS))) {
I left this comment to get verification on the logic of how the `if` is implemented too. Is the logic appropriate? 

Will move it to its own method too.

2024-11-01 09:50 UTC, karan-j-blc commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/UpgradeSubscriptionHandler.java
> +    private CartOperationProvider<Cart> cartOperationProvider;
I looked at all the concrete classes of `AbstractModifySubscriptionHandler` and see that each of them have `policyUtils` plugged in like this:
``` java
@Getter(value = AccessLevel.PROTECTED, onMethod_ = @Nullable)
@Setter(onMethod_ = @Autowired(required = false))
private TrackablePolicyUtils policyUtils;
```

And it is present in the `AbstractModifySubscriptionHandler` like this:
``` java
@Nullable
protected abstract TrackablePolicyUtils getPolicyUtils();
```

Do we really need an _abstract method_ for it then? 

I feel that we can remove the abstract method and add it in the same way `TypeFactory` is added. 

Thoughts?

2024-11-01 10:56 UTC, karan-j-blc commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/DowngradeSubscriptionHandler.java
> +        addDependentsToParents(subscriptionItemIdsToChildrenIds, addItemRequestMap);
If I understand this correctly, I need to create a `newSubscriptionItem`, persist it and it to the `subscriptionItems` list right?

2024-11-01 11:06 UTC, karan-j-blc commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/UpgradeSubscriptionHandler.java
> +        addDependentsToParents(subscriptionItemIdsToChildrenIds, addItemRequestMap);
Added some questions in the code in _// todos_

Same question for DowngradeSubscriptionHandler

2024-11-01 12:56 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +    public final TypeFactory typeFactory;
We have the protected getter so that it can be accessed via child classes

2024-11-01 13:08 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/DowngradeSubscriptionHandler.java
> +        addDependentsToParents(subscriptionItemIdsToChildrenIds, addItemRequestMap);
No, initiating upgrades/downgrades, edits, etc. is all about setting up a **cart** so that the customer can leverage typical PDPs to describe the updates that they want. With that, we do **not** want to modify the subscription, until that cart is submitted.

In the context of an upgrade, downgrade, or edit, we want to establish a cart with the relevant action flow value, record a representation the original state of the subscription, & establish the relevant cart items. In the case of an upgrade/downgrade, the cart items should reflect the targeted upgrade or downgrade item, _instead of_ the current subscription items.

2024-11-01 13:27 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/UpgradeSubscriptionHandler.java
> +    private CartOperationProvider<Cart> cartOperationProvider;
I suspect that TrackablePolicyUtils requires special treatment. _Why_ is unclear to me, but we should generally use our typical constructor pattern.

2024-11-01 14:55 UTC, karan-j-blc commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/UpgradeSubscriptionHandler.java
> +    private CartOperationProvider<Cart> cartOperationProvider;
So, do you mean I keep it as it is? Or add it as a constructor param?

2024-11-01 14:59 UTC, karan-j-blc commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/UpgradeSubscriptionHandler.java
> +        // newSubscriptionItem.setItemUnitPrice(request.getChangeTo().get);
@ckittrell How do I setup the price here? Or can I skip it entirely?

2024-11-01 15:00 UTC, karan-j-blc commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/UpgradeSubscriptionHandler.java
> +        subscriptionItems.add(newSubscriptionItem);
@ckittrell I get that I don't need to persist the `newSubscriptionItem`. Is this how you imagined the flow to be?

2024-11-04 12:51 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/UpgradeSubscriptionHandler.java
> +        subscriptionItems.add(newSubscriptionItem);
I'm surprised to see SubscriptionItem at all here.

I'd expect us to get the upgrade product identified by the request & add it to cart using the default configs for any related add-ons.

2024-11-04 12:51 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/UpgradeSubscriptionHandler.java
> +        // newSubscriptionItem.setItemUnitPrice(request.getChangeTo().get);
I don't think this is directionally correct. See comments above

2024-11-05 04:53 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/UpgradeSubscriptionHandler.java
> +        setExistingAndNewProductsOnModifySubscriptionRequest(request, contextInfo);
Instead of shoe-horning this into the validateRequest method, I'd rather see us introduce a `hydrateRequest(...)` method in the abstract class that gets called just before executing validation. From there, upgrade & downgrade can have implementations of this new method.

2024-11-05 04:53 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/DowngradeSubscriptionHandler.java
> +    }
A few things here...
- I'd move this method just below where it's called
- The method chaining for `subscriptionCreatedInstant` is asking for a bad NPE where you can't tell what's null. Split this into a reasonable set of fields in the method.
- This condition needs to check against the subscription's last bill date (a field not currently recorded on the subscription, but needs to be added) - ie each billing cycle re-opens the window to potentially downgrade.

2024-11-05 04:53 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +    }
These methods are now only called by the edit handler, so they should be moved back to that specific handler.

2024-11-05 04:53 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/InitiateDowngradeSubscriptionHandler.java
> +        addItemRequest.setQuantity(1);
If it's not null, the quantity needs to be set to `Product#minimumThreshold`. Otherwise set it to 1.

2024-11-05 04:53 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/InitiateUpgradeSubscriptionHandler.java
> +        addItemRequest.setQuantity(1);
If it's not null, the quantity needs to be set to `Product#minimumThreshold`. Otherwise set it to 1.

2024-11-05 04:53 UTC, ckittrell commented on services/src/test/java/com/broadleafcommerce/subscriptionoperation/service/InitiateDowngradeSubscriptionHandlerTest.java
> +    }
Nitpick: Give these some whitespace so you can easily tell what's setup vs calling the thing that you want to test vs checking the result

2024-11-05 04:53 UTC, ckittrell commented on services/src/test/java/com/broadleafcommerce/subscriptionoperation/service/InitiateDowngradeSubscriptionHandlerTest.java
> +public class InitiateDowngradeSubscriptionHandlerTest {
It's also worth testing the validation components

2024-11-05 04:53 UTC, ckittrell commented on services/src/test/java/com/broadleafcommerce/subscriptionoperation/service/InitiateDowngradeSubscriptionHandlerTest.java
> +                .createCart(createCartRequestCaptor.capture(), eq(null));
This test should be moved to the same directory path as the actual class. For example:
- `src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/InitiateDowngradeSubscriptionHandler.java`
- `src/test/java/com/broadleafcommerce/subscriptionoperation/service/modification/InitiateDowngradeSubscriptionHandlerTest.java`

`/modification` is currently missing from the test path.

By doing so, you can call `handler.buildCreateCartRequest(...)` directly to verify the payload contents.

It doesn't hurt to do an end-to-end test like this also, but I get the impression that you're mostly doing this setup to verify the CreateCartRequest.

2024-11-05 04:53 UTC, ckittrell commented on services/src/test/java/com/broadleafcommerce/subscriptionoperation/service/InitiateDowngradeSubscriptionHandlerTest.java
> +                .matches("DOWNGRADE %s - \\w{26}".formatted(TestObjectCreator.SUBSCRIPTION_NAME));
This needs more assertions about the CreateCartRequest & AddItemRequest!!

The assertions currently here don't really verify anything meaningful yet.

2024-11-05 04:53 UTC, ckittrell commented on services/src/test/java/com/broadleafcommerce/subscriptionoperation/service/InitiateUpgradeSubscriptionHandlerTest.java
> +public class InitiateUpgradeSubscriptionHandlerTest {
The same feedback on the downgrade test apply here.

2024-11-05 09:28 UTC, karan-j-blc commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/UpgradeSubscriptionHandler.java
> +    public boolean canHandle(@NonNull ModifySubscriptionRequest request,
It is already using `@lombok.NonNull` as can be verified from the imports. Is there a special preference/pattern to use the `lombok.` prefix there?

2024-11-05 10:28 UTC, karan-j-blc commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/DowngradeSubscriptionHandler.java
> +    }
> This condition needs to check against the subscription's last bill date (a field not currently recorded on the subscription, but needs to be added) - ie each billing cycle re-opens the window to potentially downgrade.

Isn't [this](https://github.com/BroadleafCommerce/SubscriptionOperationServices/blob/eb618c2ac6a267f4bb77f6dd9b519658ba887b07/services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/Subscription.java#L243) what we are looking for?

2024-11-05 10:44 UTC, karan-j-blc commented on services/src/test/java/com/broadleafcommerce/subscriptionoperation/service/InitiateDowngradeSubscriptionHandlerTest.java
> +                .createCart(createCartRequestCaptor.capture(), eq(null));
Yes, the test is mostly for checking that the CreateCartRequest is built correctly.

2024-11-05 13:24 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/DowngradeSubscriptionHandler.java
> +    }
Not necessarily. A subscription may _not_ be billed on its bill date exactly. The most common cause of this is that the payment failed & we need to retry on another day (much more of a MLB scenario than a VFE scenario). In that case, the `lastBillingSuccessDate` will reflect the day on which the payment transaction was successfully retried, not the last bill date itself.

Long story short, we can't use that value for this purpose.

2024-11-05 13:28 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/UpgradeSubscriptionHandler.java
> +    public boolean canHandle(@NonNull ModifySubscriptionRequest request,
We need to use `@lombok.NonNull` for request params & don't want to use the import. Instead, we want to allow Spring's `@NonNull` to be imported when/where we need to use it. This is meant to clearly distinguish the two separate concerns, driven by annotations with the same name.

More details on this from our SDLC: https://github.com/BroadleafCommerce/MicroservicesInternalDev/wiki/Service-Developer-Guidelines#required-fields

2024-11-05 14:25 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/Product.java
> +    private Integer minimumThreshold;
You'll need to get info from the ProductOptions as well, so you might as well copy that domain over.

2024-11-05 14:45 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +    @Getter(value = AccessLevel.PROTECTED, onMethod_ = @Nullable)
Not sure why this would be nullable.
```suggestion
    @Getter(value = AccessLevel.PROTECTED)
```

2024-11-05 14:45 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +    protected void hydrateRequest(@NonNull ModifySubscriptionRequest request,
Javadocs on all protected methods indicating what they are for and where they are called from. Abstract classes can get confusing.

2024-11-05 14:45 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +    protected Pair<Product, Product> readNewAndRootItems(
Better to either return the list as is or to create a custom DTO than to use a `Pair`.

2024-11-05 14:45 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +            @Nullable ContextInfo contextInfo) {}
Why does this exist if we have the other? Would anyone ever use it? How are we expecting them to get the Products without a `CatalogProvider`?

2024-11-05 14:45 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +            @NonNull CatalogProvider<Product> catalogProvider,
Why not just inject a bean instead?

2024-11-05 14:45 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +            @Nullable ContextInfo contextInfo) {
Also this present an extension challenge if you don't use generics and they've extended the Product domain
```suggestion
    protected <T extends Product> void setExistingAndNewProductsOnModifySubscriptionRequest(
            @NonNull ModifySubscriptionRequest request,
            @NonNull CatalogProvider<T> catalogProvider,
            @Nullable ContextInfo contextInfo) {
```

2024-11-05 14:45 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +            @Nullable ContextInfo contextInfo) {
Better to be more generic to support future needs that may require more products to be read. The caller can figure out which Product is which since they know what they were asking for.
```suggestion
    protected <T extends Product> List<T> readNewAndRootItems(
            @NonNull ModifySubscriptionRequest request,
            @NonNull CatalogProvider<T> catalogProvider,
            @Nullable ContextInfo contextInfo) {
```

2024-11-05 14:45 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +            @Nullable ContextInfo contextInfo) {
I would have assumed they'd still want the `CatalogProvider` or else how will the fetch the products?
```suggestion
    protected <T extends Product> List<T> readNewAndRootItemsByCustomReferences(
            @NonNull ModifySubscriptionRequest request,
            @NonNull CatalogProvider<T> catalogProvider,
            @Nullable ContextInfo contextInfo) {
```

2024-11-05 14:45 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/InitiateEditSubscriptionHandler.java
> +            @lombok.NonNull String operationFlowName) {
The edit handler always uses the edit flow, so why include this as a param here?

2024-11-05 14:45 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +    protected void hydrateRequest(@NonNull ModifySubscriptionRequest request,
Should be named more clearly as to what's going on here
```suggestion
    protected void hydrateAdditionalModificationState(@NonNull ModifySubscriptionRequest request,
```

2024-11-05 14:45 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +    protected Pair<Product, Product> readNewAndRootItems(
Questioning why this method returns any information rather than just adding the Products directly to the `ModifySubscriptionRequest` since it's already present. It would reduce complexity.

2024-11-05 20:44 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +    protected Pair<Product, Product> readNewAndRootItems(
This and other comments for these methods are moot with the changes I made in this PR https://github.com/BroadleafCommerce/SubscriptionOperationServices/pull/20.

2024-11-05 20:44 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +            @NonNull CatalogProvider<Product> catalogProvider,
My comment is moot with the changes I made in this PR https://github.com/BroadleafCommerce/SubscriptionOperationServices/pull/20.

2024-11-05 20:45 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +            @Nullable ContextInfo contextInfo) {
My comment is moot with the changes I made in this PR https://github.com/BroadleafCommerce/SubscriptionOperationServices/pull/20.

2024-11-05 20:45 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +            @Nullable ContextInfo contextInfo) {
My comment is moot with the changes I made in this PR https://github.com/BroadleafCommerce/SubscriptionOperationServices/pull/20.

2024-11-05 20:45 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +            @Nullable ContextInfo contextInfo) {
My comment is moot with the changes I made in this PR https://github.com/BroadleafCommerce/SubscriptionOperationServices/pull/20.

2024-11-05 20:46 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +    protected void hydrateRequest(@NonNull ModifySubscriptionRequest request,
My comment is moot with the changes I made in this PR https://github.com/BroadleafCommerce/SubscriptionOperationServices/pull/20.

2024-11-05 20:46 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractModifySubscriptionHandler.java
> +    protected Pair<Product, Product> readNewAndRootItems(
My comment is moot with the changes I made in this PR https://github.com/BroadleafCommerce/SubscriptionOperationServices/pull/20.

2024-11-06 13:52 UTC, nathandmoore reviewed
Some minor cleanup

2024-11-06 13:52 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/ItemChoice.java
> +    // private String selectionType;
Shouldn't be commented out.

2024-11-06 13:52 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/ItemChoice.java
> +    // private Product defaultProductInCategory;
Shouldn't be commented out. We don't actually care about these fields in this context, so like on Product, add an `additionalAttributes` (not `attributes` since that field is a first class field on `ProductOption`) map with a getter and setter annotated with `@JsonAnyGetter` and `@JsonAnyGetter` to catch all the other properties we don't need to enumerate in Sub Ops.

2024-11-06 13:52 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/ItemChoice.java
> +    // private Variant defaultVariant;
Just remove instead of comment out

2024-11-06 13:52 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/ItemChoice.java
> +    // private SpecificItemChoice specificItemChoice;
We'll need these later, I think. So uncomment them and copy over `SpecificItemChoice`

2024-11-06 13:52 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/ItemChoice.java
> +    // }
I think we can just remove these as well.

2024-11-06 13:52 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/ProductOption.java
> +    // private boolean addedByReference = false;
Same as with ItemChoice, add an `additionalAttributes` map and remove these commented out fields.

2024-11-06 13:52 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/ProductOption.java
> +    // private AttributeChoice attributeChoice;
We probably don't need to enumerate this, so remove it. It will end up in the `additionalAttributes`.

2024-11-06 16:16 UTC, karan-j-blc commented
@nathandmoore, @ckittrell I've added the `SpecificItemChoice` and `Variant` domains here. 

Also commented out the fields I don't think are necessary. Can you please take a look and let me know if there are some changes there?

2024-11-06 23:04 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/SpecificItemChoice.java
> +    // private MonetaryAmount overridePrice;
Default assumption should be that we need a field

2024-11-06 23:06 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/SpecificItemChoice.java
> +    // private SpecificItemChoiceAsset asset;
Then we can evaluate whether we could possibly use the field to see if we can remove it. Like here, we don't need assets for anything in Sub Ops.
```suggestion
```

2024-11-06 23:12 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/Variant.java
> +    // private Weight weight;
We don't really have any reason to use these fields in Sub Ops.
```suggestion
```

2024-11-06 23:12 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/Variant.java
> +    // private ReviewsSummary reviewsSummary;
```suggestion
```

2024-11-06 23:12 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/Variant.java
> +    // private DataDrivenEnum fulfillmentWorkflow;
We aren't working with fulfillment here.
```suggestion
```

2024-11-06 23:12 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/Variant.java
> +
```suggestion
```

2024-11-06 23:12 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/SpecificItemChoice.java
> +
Hmm, I think this is from an unused feature. 
```suggestion
```

2024-11-06 23:12 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/SpecificItemChoice.java
> +    // }
```suggestion
```

2024-11-06 23:12 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/SpecificItemChoice.java
> +    // private MonetaryAmount overridePrice;
Actually, nevermind. We'd let Cart Ops or Order Ops handle prices
```suggestion
```

2024-11-07 13:43 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractGradeChangeSubscriptionModificationHandler.java
> +            @Nullable ContextInfo contextInfo) {
For strings, we generally would consider a blank string to also be an illegal argument. So instead of just checking for null with lombok, we instead use Spring's `Assert.hasText` 

```suggestion
    protected AddItemRequest createAddItemRequestForGradeChangeProduct(
            @lombok.NonNull ModifySubscriptionRequest request,
            String flowName,
            @Nullable ContextInfo contextInfo) {
            Assert.hasText(flowName, "FlowName cannot be blank");
```

2024-11-07 13:43 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractGradeChangeSubscriptionModificationHandler.java
> +        }
I think we would look at the existing subscription root item's quantity first, and use it as long as it is greater than the minimum threshold. I doubt we'd ever need to default to quantity 1 for ugprade/downgrade.

2024-11-07 13:43 UTC, nathandmoore commented on services/src/test/java/com/broadleafcommerce/subscriptionoperation/service/modification/InitiateDowngradeSubscriptionHandlerTest.java
> +        assertThrows(ValidationException.class, () -> handler.handle(request, null));
Also check the specific errors, the field and the code, to make sure the right things are flagged.

2024-11-07 13:43 UTC, nathandmoore commented on services/src/test/java/com/broadleafcommerce/subscriptionoperation/service/modification/InitiateDowngradeSubscriptionHandlerTest.java
> +        assertThrows(ValidationException.class, () -> handler.handle(request, null));
Also check the specific errors, the field and the code, to make sure the right things are flagged.

2024-11-07 14:02 UTC, karan-j-blc commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractGradeChangeSubscriptionModificationHandler.java
> +        }
This makes sense and should be populated in almost every case. 

The else block should still set it to 1 though right?

2024-11-07 14:11 UTC, nathandmoore commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/modification/AbstractGradeChangeSubscriptionModificationHandler.java
> +        }
It shouldn't be needed. It should just copy the existing or use the minimum threshold, so `Math.max(existing, minimum)`. The existing cannot be null, so there's no need for the fallback on the main item.

2024-11-07 15:49 UTC, nathandmoore approved these changes

2024-11-07 16:45 UTC, nathandmoore approved these changes

2024-11-07 16:52 UTC, merged