Add events' listener & producer
BroadleafCommerce/SubscriptionOperationServices pull request #2
Opened 2024-09-10 18:59 UTC by kboiko2

- Adds default config properties
- Adds a sample dummy listener for OrderCreatedEvent
- Adds a sample dummy producer for SubscriptionCreatedEvent
- Adds IT tests

2024-09-24 14:58 UTC, ckittrell requested changes

2024-09-24 14:58 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/SubscriptionOperationService.java
> +    S upgradeSubscription(SubscriptionChangeTierRequest changeTierRequest, ContextInfo contextInfo);
Javadocs needed!

2024-09-24 14:58 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/domain/enums/SubscriptionStatuses.java
> +    ERROR;
Javadocs needed!

2024-09-24 14:58 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/provider/jpa/environment/SubscriptionOperationProviderProperties.java
> +    private String provider = "none";
Javadocs needed!

2024-09-24 14:58 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/autoconfigure/SubscriptionOperationServiceAutoConfiguration.java
> +    }
Nitpick: it'd be good to separate this into a messaging/JPA auto-config class

2024-09-24 14:58 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/provider/SubscriptionProvider.java
> +            ContextInfo contextInfo);
Javadocs!

2024-09-24 14:58 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/provider/external/ExternalSubscriptionProperties.java
> +     * The service client to use when calling billing services. Default is "subscription".
```suggestion
     * The service client to use when calling billing services. Default is "subscriptionopsclient".
```

2024-09-24 14:58 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/provider/external/ExternalSubscriptionProvider.java
> +                .orElseThrow(EntityMissingException::new));
Seems like an empty page should be returned on the `.orElse...`

2024-09-24 14:58 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/web/domain/SubscriptionCancellationRequest.java
> +    private boolean immediateCancellation;
Leaving this as-is is fine, given that this is mostly a placeholder at the moment

2024-09-24 14:58 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/web/domain/SubscriptionCreationRequest.java
> + */
Javadocs needed!

2024-09-24 14:58 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/web/endpoint/AccountSubscriptionOperationEndpoint.java
> +    }
If I understand correctly, this endpoint is meant to be customer-facing. Assuming that's right, then verifying that only members of that account can access the data is very important.

Note: I believe that when ownership is checked via a Policy annotation, that the permission is NOT also checked. In this case, we want to check both. This may call for account-based checks within the endpoint method, rather than via the Policy annotation.

TODOs:
- [ ] Add tests verifying the enforcement of the Policy annotation
- [ ] Refine the permission vs ownership checks

2024-09-24 14:58 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/web/endpoint/CustomerSubscriptionOperationEndpoint.java
> +    }
Similar note about the enforcement of the Policy annotation: we need tests verifying access. 

For example, do you gain access with only the permission, even if you're not the owner?

The key piece of the ownership check is that the id provided in the uri matches the authed customer's id.

Also consider that since we have System endpoints, the Admin IdentityType shouldn't be needed.

2024-09-24 14:58 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/web/endpoint/CustomerSubscriptionOperationEndpoint.java
> +    }
These are placeholders, but lets also get the security pieces right, while we're in the area.

2024-09-24 14:58 UTC, ckittrell commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/provider/external/ExternalSubscriptionProperties.java
> +    private String subscriptionUri;
Should probably just provide the default value here, instead of in the yml file

2024-09-24 18:48 UTC, kboiko2 commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/web/endpoint/CustomerSubscriptionOperationEndpoint.java
> +    }
Agreed, tests would be useful. I just added [a test](https://github.com/BroadleafCommerce/SubscriptionOperationServices/pull/2/commits/fe5bdd7d85f1b265305d06a3b7e8d19eccec8bb1) for the customer endpoint's access. It passed with flying colors, you need both the permission and the right customer id to gain access. 

Also just removed the admin identityType

Next on my list is the Account endpoint access

2024-09-24 18:55 UTC, kboiko2 commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/service/provider/external/ExternalSubscriptionProvider.java
> +                .orElseThrow(EntityMissingException::new));
Not sure why we use this pattern, but I can't find a single provider that does not throw while returning a page. Potentially, an empty page is a valid client response vs not being able to map to a page is cause for an error?

2024-09-24 21:01 UTC, kboiko2 commented on services/src/main/java/com/broadleafcommerce/subscriptionoperation/web/endpoint/AccountSubscriptionOperationEndpoint.java
> +    }
Judging by the IT test results I am receiving, this way ownership is checked via the policy annotation, and the permission is verified as well. This is incline with our previous endpoints for Account things from CartOps and Customer

2024-10-02 15:59 UTC, ckittrell approved these changes
Approving with the intention of merging to unblock the VFE starter.

Will revisit while reviewing the [related OrderOps work](https://github.com/BroadleafCommerce/OrderOperationServices/pull/311) & open another PR if necessary.

2024-10-02 16:00 UTC, merged